### ISSUE TITLE
Throw an error when there are no available sites/groups

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/generator-liferay-fragments#52]
If you login with an user that has no access to any site or group, CLI shows an empty list instead of showing that as an error.

**Comment by kyle-miho** [comment]
We may want to be considerate about permissions as well. What happens if a user has site view permissions, but no manage fragment permissions (the user can technically see the site, but they can't modify fragments for the site)

Maybe if the user can view the site and fragments of a site, but cannot edit them (most site members without permissions required), then there should be a way to notify them they do not have permissions
