### ISSUE TITLE
Fragments Don't Update on Page

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/generator-liferay-fragments#98]
o Create a new collection with fragment F1
o Place fragment F1 on some content page P1
o Publish page P1
o Make an update to fragment F1. Update is **not** reflected on page P1.

Is this expected behavior or did i do something wrong?

**Comment by ruben-pulido** [comment]
This is expected behaviour.
Per default, changes to fragments are not automatically propagated to fragments in pages.
Changes can be manually propagated following the steps described here: 
https://portal.liferay.dev/docs/7-2/user/-/knowledge_base/u/propagation-of-changes

It is also possible to configure automatic propagation of changes in:
Configuration > Instance Settings > Page Fragments > Propagate Fragment Changes Automatically
